version: '3.9'

services:
  api:
    build:
      context: ./backend
    image: api
    container_name: api
    env_file: ./backend/src/variables.env
    restart: unless-stopped
    network_mode: 'host'
    networks:
      - app-network

  admin:
    build:
      context: ./dashboard
    image: admin
    container_name: admin
    env_file: ./dashboard/.env.local
    depends_on:
      - 'api'
    restart: unless-stopped
    network_mode: 'host'
    networks:
      - app-network

  client:
    build:
      context: ./client
    image: client
    container_name: client
    env_file: ./client/.env.local
    depends_on:
      - 'api'
    restart: unless-stopped
    network_mode: 'host'
    networks:
      - app-network

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    depends_on:
      - api
      - admin
      - client
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - URL=t.onthecourt.store
      - SUBDOMAINS=www,
        # admin,www.admin,api,www.api
      - VALIDATION=http
      - EMAIL=soporte@avilatek.dev
      - STAGING=true #optional
    volumes:
      - ./site-confs:/config/nginx/site-confs
      - ./proxy-confs:/config/nginx/proxy-confs
    network_mode: 'host'
    networks:
      - app-network
    network_mode: 'host'
    # ports:
    #   - '80:80'
    #   - '443:443'

networks:
  app-network:
    driver: bridge
