import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { NextAuthProvider } from '@/context/auth-provider';
import { ApolloWrapper } from '@/context/apollo-context';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable
        )}
      >
        <ApolloWrapper>
          {/* <NextAuthProvider> */}
          {children}
          {/* </NextAuthProvider> */}
        </ApolloWrapper>
      </body>
    </html>
  );
}
