import { ApolloWrapper } from '../context/ApolloContext';
import { NextAuthProvider } from '../context/AuthContext';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
