name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-containers:
    name: 'Build Containers'
    environment: staging
    runs-on: ['self-hosted', 'staging']

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build images
        working-directory: ./
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          PORT: ${{ secrets.PORT }}
          DATABASE: ${{ secrets.DATABASE_STG }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID_STG }}
          ALGOLIA_PUBLIC_KEY: ${{ secrets.ALGOLIA_PUBLIC_KEY_STG }}
          ALGOLIA_PRIVATE_KEY: ${{ secrets.ALGOLIA_PRIVATE_KEY_STG }}
          SECRET: ${{ secrets.SECRET }}
          CORS_ORIGINS: ${{ secrets.CORS_ORIGINS_STG }}
          CLIENT_URL: ${{ secrets.CLIENT_URL_STG }}
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL_STG }}
          POSTMARK_API_KEY: ${{ secrets.POSTMARK_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INTERCONECTADOS_USER: ${{ secrets.INTERCONECTADOS_USER_STG }}
          INTERCONECTADOS_PASSWORD: ${{ secrets.INTERCONECTADOS_PASSWORD_STG }}
          NEXT_PUBLIC_GOOGLE_MAPS_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_KEY }}
          NEXT_PUBLIC_TINY_KEY: ${{ secrets.NEXT_PUBLIC_TINY_KEY }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_PROJECT_API: ${{ secrets.SENTRY_PROJECT_API }}
          SENTRY_PROJECT_CLIENT: ${{ secrets.SENTRY_PROJECT_CLIENT }}
          SENTRY_PROJECT_ADMIN: ${{ secrets.SENTRY_PROJECT_ADMIN }}
          SENTRY_DSN_API: ${{ secrets.SENTRY_DSN_API }}
          NEXT_PUBLIC_SENTRY_DSN_ADMIN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN_ADMIN }}
          NEXT_PUBLIC_SENTRY_DSN_CLIENT: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN_CLIENT }}
          EMAILS: ${{ secrets.EMAILS }}
        run: |
          chmod 600 letsencrypt/acme.json
          touch ./.env ./apps/api/src/variables.env ./apps/admin/.env.local ./apps/admin/sentry.properties ./apps/client/.env.local ./apps/client/sentry.properties
          # SENTRY
          echo "SENTRY_URL=$SENTRY_URL" >> ./.env
          echo "SENTRY_ORG=$SENTRY_ORG" >> ./.env
          echo "SENTRY_TOKEN=$SENTRY_TOKEN" >> ./.env
          echo "SENTRY_PROJECT_API=$SENTRY_PROJECT_API" >> ./.env
          echo "SENTRY_PROJECT_CLIENT=$SENTRY_PROJECT_CLIENT" >> ./.env
          echo "SENTRY_PROJECT_ADMIN=$SENTRY_PROJECT_ADMIN" >> ./.env
          echo "SENTRY_DSN_API=$SENTRY_DSN_API" >> ./.env
          echo "NEXT_PUBLIC_SENTRY_DSN_ADMIN=$NEXT_PUBLIC_SENTRY_DSN_ADMIN" >> ./.env
          echo "NEXT_PUBLIC_SENTRY_DSN_CLIENT=$NEXT_PUBLIC_SENTRY_DSN_CLIENT" >> ./.env
          echo "TURBO_TEAM=$TURBO_TEAM" >> ./.env
          echo "TURBO_TOKEN=$TURBO_TOKEN" >> ./.env
          # BACKEND
          echo "NODE_ENV=$NODE_ENV" >> ./apps/api/src/variables.env
          echo "PORT=$PORT" >> ./apps/api/src/variables.env
          echo "DATABASE=$DATABASE" >> ./apps/api/src/variables.env
          echo "ALGOLIA_APP_ID=$ALGOLIA_APP_ID" >> ./apps/api/src/variables.env
          echo "ALGOLIA_PUBLIC_KEY=$ALGOLIA_PUBLIC_KEY" >> ./apps/api/src/variables.env
          echo "ALGOLIA_PRIVATE_KEY=$ALGOLIA_PRIVATE_KEY" >> ./apps/api/src/variables.env
          echo "SECRET=$SECRET" >> ./apps/api/src/variables.env
          echo "CORS_ORIGINS=$CORS_ORIGINS" >> ./apps/api/src/variables.env
          echo "CLIENT_URL=$CLIENT_URL" >> ./apps/api/src/variables.env
          echo "DASHBOARD_URL=$DASHBOARD_URL" >> ./apps/api/src/variables.env
          echo "POSTMARK_API_KEY=$POSTMARK_API_KEY" >> ./apps/api/src/variables.env
          echo "SENDER_EMAIL=$SENDER_EMAIL" >> ./apps/api/src/variables.env
          echo "AWS_BUCKET_NAME=$AWS_BUCKET_NAME" >> ./apps/api/src/variables.env
          echo "AWS_REGION=$AWS_REGION" >> ./apps/api/src/variables.env
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> ./apps/api/src/variables.env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> ./apps/api/src/variables.env
          echo "INTERCONECTADOS_USER=$INTERCONECTADOS_USER" >> ./apps/api/src/variables.env
          echo "INTERCONECTADOS_PASSWORD=$INTERCONECTADOS_PASSWORD" >> ./apps/api/src/variables.env
          echo "SENTRY_DSN=$SENTRY_DSN_API" >> ./apps/api/src/variables.env
          echo "TURBO_TEAM=$TURBO_TEAM" >> ./apps/api/src/variables.env
          echo "TURBO_TOKEN=$TURBO_TOKEN" >> ./apps/api/src/variables.env
          # ADMIN
          echo "NEXT_PUBLIC_GOOGLE_MAPS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_KEY" >> ./apps/admin/.env.local
          echo "NEXT_PUBLIC_ALGOLIA_APP_ID=$ALGOLIA_APP_ID" >> ./apps/admin/.env.local
          echo "NEXT_PUBLIC_ALGOLIA_PUBLIC_KEY=$ALGOLIA_PUBLIC_KEY" >> ./apps/admin/.env.local
          echo "NEXT_PUBLIC_TINY_KEY=$NEXT_PUBLIC_TINY_KEY" >> ./apps/admin/.env.local
          echo "NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN_ADMIN" >> ./apps/admin/.env.local
          echo "TURBO_TEAM=$TURBO_TEAM" >> ./apps/admin/.env.local
          echo "TURBO_TOKEN=$TURBO_TOKEN" >> ./apps/admin/.env.local
          # CLIENT
          echo "NEXT_PUBLIC_GOOGLE_MAPS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_KEY" >> ./apps/client/.env.local
          echo "NEXT_PUBLIC_ALGOLIA_APP_ID=$ALGOLIA_APP_ID" >> ./apps/client/.env.local
          echo "NEXT_PUBLIC_ALGOLIA_PUBLIC_KEY=$ALGOLIA_PUBLIC_KEY" >> ./apps/client/.env.local
          echo "NEXT_PUBLIC_TINY_KEY=$NEXT_PUBLIC_TINY_KEY" >> ./apps/client/.env.local
          echo "NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN_CLIENT" >> ./apps/client/.env.local
          echo "TURBO_TEAM=$TURBO_TEAM" >> ./apps/client/.env.local
          echo "TURBO_TOKEN=$TURBO_TOKEN" >> ./apps/client/.env.local
          # DOCKER
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose up --build -d --scale api=3 --scale admin=3 --scale client=3
          docker system prune -f
          curl --location --request POST 'https://avila-mail.vercel.app/api/lark' \
          --header 'Content-Type: application/json' \
          --data '{
              "action": "deploy",
              "project_name": "Nuevo Proyecto",
              "env": "staging",
              "links": ["$CLIENT_URL", "$DASHBOARD_URL"],
              "gh_action": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID",
              "emails": "$EMAILS"
          }'

      - name: Build failed
        if: ${{ failure() }}
        run: |
          curl --location --request POST 'https://avila-mail.vercel.app/api/lark' \
          --header 'Content-Type: application/json' \
          --data '{
              "action": "failure",
              "project_name": "Nuevo Proyecto",
              "env": "staging",
              "links": ["$CLIENT_URL", "$DASHBOARD_URL"],
              "gh_action": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID",
              "emails": "$EMAILS"
          }'
